apiVersion: v1
kind: PersistentVolume
metadata:
  name: freshrss-config-pv
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: freshrss
    name: freshrss-config
  storageClassName: nfs-storage
  nfs:
    server: <nfs-server>
    path: /data/freshrss
