apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-config
  namespace: calibre
spec:
  storageClassName: nfs-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
