apiVersion: apps/v1
kind: Deployment
metadata:
  name: convertx
  namespace: convertx
  labels:
    app: convertx
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: convertx
  template:
    metadata:
      labels:
        app: convertx
    spec:
      containers:
      - name: convertx
        image: c4illin/convertx
        ports:
        - containerPort: 3000
          name: http
        volumeMounts:
        - name: data
          mountPath: /app/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: convertx-data
