apiVersion: v1
kind: PersistentVolume
metadata:
  name: convertx-data-pv
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: <nfs-server>
    path: /data/convertx
