apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv
spec:
  local:
    path: /data/plex/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - atlas
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-pv
spec:
  local:
    path: /media
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - atlas
