apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-data-pv
spec:
  nfs:
    server: 192.168.0.176
    path: /mdata/prometheus
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-data-pv
spec:
  nfs:
    server: 192.168.0.176
    path: /mdata/loki
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-data-pv
spec:
  nfs:
    server: 192.168.0.176
    path: /mdata/grafana
