apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-data-pv
spec:
  local:
    path: /data/prometheus
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - atlas
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-data-pv
spec:
  local:
    path: /data/loki
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - atlas
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-data-pv
spec:
  local:
    path: /data/grafana
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - atlas
