apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filebrowser
  namespace: filebrowser
spec:
  rules:
  - host: files.zahariev.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: filebrowser
            port:
              number: 80
  tls:
  - hosts:
    - files.zahariev.com
    secretName: filebrowser-tls
