apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config-pv
spec:
  local:
    path: /data/qbittorrent/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - hyperion
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-downloads-pv
spec:
  local:
    path: /ssd/downloads
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - hyperion
