apiVersion: v1
kind: PersistentVolume
metadata:
  name: workers-tasks-pv
spec:
  nfs:
    server: 192.168.0.55
    path: /mnt/media/tasks
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: workers-handbrake-input-pv
spec:
  local:
    path: /media/handbrake/input
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - atlas
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: workers-handbrake-output-pv
spec:
  local:
    path: /media/handbrake/output
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - atlas
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: workers-downloads-pv
spec:
  local:
    path: /media/downloads
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - atlas
