apiVersion: v1
kind: PersistentVolume
metadata:
  name: workers-tasks-pv
spec:
  nfs:
    server: 192.168.0.176
    path: /ssd/tasks
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: workers-handbrake-input-pv
spec:
  local:
    path: /ssd/handbrake/input
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - hyperion
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: workers-handbrake-output-pv
spec:
  local:
    path: /ssd/handbrake/output
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - hyperion
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: workers-downloads-pv
spec:
  local:
    path: /ssd/downloads
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - hyperion
