apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: home-lab
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: https://github.com/dzahariev/home-lab.git
      revision: HEAD
      directories:
      - path: cluster/overlays/zahariev.com/*
  template:
    metadata:
      name: "{{ .path.basename }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/dzahariev/home-lab.git
        targetRevision: HEAD
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
