apiVersion: v1
kind: PersistentVolume
metadata:
  name: changedetection-data-pv
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: changedetection
    name: changedetection-data
  storageClassName: nfs-storage
  nfs:
    server: <nfs-server>
    path: /data/changedetection
