apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stirling
  namespace: stirling
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  - host: stirling.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stirling
            port:
              number: 8080
  tls:
  - hosts:
    - stirling.example.com
    secretName: stirling-tls
