apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stirling-data
  namespace: stirling
spec:
  storageClassName: nfs-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
